name: CI

on:
  push:
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build -c Release --no-restore
    - name: Publish All
      run: dotnet publish -c Release -o ./artifacts/all
    - uses: actions/upload-artifact@v2
      with:
        name: all-artifacts
        path: ./artifacts/all
    - name: Publish Api
      run: dotnet publish ./BookApi -c Release -o ./artifacts/book-api
    - uses: actions/upload-artifact@v2
      with:
        name: book-api-artifacts
        path: ./artifacts/book-api
    - name: script
      run: |
        ls
      
      
  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/download-artifact@v2
      with:
        name: all-artifacts
        path: .
    - name: script
      run: ls
    - name: Test
      run: dotnet test --verbosity normal
